# Generated by Django 6.0.4 on 2026-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_icon_remove_technology_icon_key_technology_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='icon',
            new_name='icon_key',
        ),
        migrations.AddField(
            model_name='icon',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
