# Generated by Django 6.0.4 on 2026-04-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_icon_icon_icon_key_icon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='color',
        ),
    ]
