# Generated by Django 6.0.4 on 2026-04-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_journey_alter_project_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.RemoveField(
            model_name='project',
            name='journey',
        ),
        migrations.AddField(
            model_name='project',
            name='associated_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.journey'),
        ),
    ]
